[agent]
  hostname = "telegraf-01"


###############################################################################
#                            DATA COLLECTION                                  #
###############################################################################
[[inputs.snmp]]
  agents = ["srl1"]
  version = 2
  community = "${SNMP_COMMUNITY}"
  interval = "60s"
  timeout = "10s"
  retries = 3

  [inputs.snmp.tags]
    collection_type = "snmp"

  # `up` measurement
  [[inputs.snmp.field]]
    name = "uptime"
    # RFC1213-MIB::sysUpTime.0
    oid = "1.3.6.1.2.1.1.3.0"

 [[inputs.snmp.table]]
    name = "interface"

    [[inputs.snmp.table.field]]
      # Name of the tag used to identify the interface name.
      name = "name"
      # IF-MIB::ifDescr
      oid = "1.3.6.1.2.1.2.2.1.2"
      is_tag = true

    [[inputs.snmp.table.field]]
      # Name of the field used to identify Rx Counters.
      name = "in_octets"
      # IF-MIB::ifHCInOctets
      oid = "1.3.6.1.2.1.31.1.1.1.6"

    [[inputs.snmp.table.field]]
      # Name of the field used to identify Tx Counters.
      name = "out_octets"
      # IF-MIB::ifHCOutOctets
      oid = "1.3.6.1.2.1.31.1.1.1.10"

[[inputs.gnmi]]
  addresses = ["srl1:57400"]
  username = "${NETWORK_AGENT_USER}"
  password = "${NETWORK_AGENT_PASSWORD}"
  redial = "20s"
  tagexclude = ["path"]

  tls_enable = true
  insecure_skip_verify = true

  [inputs.gnmi.tags]
    collection_type = "gnmi"

  [[inputs.gnmi.subscription]]
    name = "interface"
    path ="/interface[name=*]/statistics"
    subscription_mode = "sample"
    sample_interval = "10s"

  [[inputs.gnmi.subscription]]
    name = "interface"
    path = "/interface[name=*]/oper-state"
    subscription_mode = "sample"
    sample_interval = "10s"

  [[inputs.gnmi.subscription]]
    name = "interface"
    path = "/interface[name=*]/admin-state"
    subscription_mode = "sample"
    sample_interval = "10s"

[[inputs.gnmi.subscription]]
  name = "cpu"
  path = "/platform/control[slot=*]/cpu[index=all]/total/instant"
  subscription_mode = "sample"
  sample_interval = "10s"

[[inputs.gnmi.subscription]]
  name = "memory"
  path = "/platform/control[slot=*]/memory/utilization"
  subscription_mode = "sample"
  sample_interval = "10s"

[[inputs.gnmi.subscription]]
  name = "bgp_peer_state"
  path = "/network-instance[name=*]/protocols/bgp/neighbor[peer-address=*]/session-state"
  subscription_mode = "sample"
  sample_interval = "10s"

[[inputs.gnmi.subscription]]
  name = "bgp_accepted_prefixes"
  path = "/network-instance[name=*]/protocols/bgp/neighbor[peer-address=*]/afi-safi[afi-safi-name=*]/received-routes"
  subscription_mode = "sample"
  sample_interval = "10s"

###############################################################################
#                               WATCHERS                                      #
###############################################################################
[[inputs.ping]]
  interval = "10s"
  count = 3
  ping_interval = 1.0
  timeout = 5.0
  urls = ["srl1"]

  [inputs.ping.tags]
    collection_type = "ping"
    watcher_type = "healthcheck"
    service = "srl1"

##############################################################################
#                            DATA NORMALIZATION                              #
##############################################################################
[[processors.rename]]
  [[processors.rename.tagpass]]
    collection_type = ["snmp"]

  [[processors.rename.replace]]
    tag = "agent_host"
    dest = "device"

  [[processors.rename.replace]]
    measurement = "snmp"
    dest = "device"


[[processors.rename]]
  [[processors.rename.tagpass]]
    collection_type = ["gnmi"]

  [[processors.rename.replace]]
    tag = "source"
    dest = "device"

  # Rename fields for CPU metrics
  [[processors.rename.replace]]
    field = "instant"
    dest = "used"

  # Rename fields for Memory metrics
  [[processors.rename.replace]]
    field = "utilized"
    dest = "used"


[[processors.rename]]
  [[processors.rename.tagpass]]
    collection_type = ["ping"]

  [[processors.rename.replace]]
    tag = "url"
    dest = "device"


# Enum processor for interface oper_status and admin_status field values to numbers
[[processors.enum]]
  namepass = ["interface"]

  [[processors.enum.tagpass]]
    collection_type = ["snmp", "gnmi"]

  [[processors.enum.mapping]]
    ## Name of the field to map
    field = "oper_state"
    [processors.enum.mapping.value_mappings]
      up = 1
      down = 2


  [[processors.enum.mapping]]
    field = "admin_state"
    [processors.enum.mapping.value_mappings]
      enable = 1
      disable = 2


###############################################################################
#                            DATA ENRICHMENT                                  #
###############################################################################
[[processors.regex]]
  namepass = ["interface"]

  [processors.regex.tagpass]
      device = ["srl1"]

  [[processors.regex.tags]]
    key = "name"
    pattern = "^ethernet.*$"
    result_key = "intf_role"
    replacement = "peer"

  [[processors.regex.tags]]
    key = "name"
    pattern = "^mgmt.*$"
    result_key = "intf_role"
    replacement = "mgmt"


##############################################################################
#                            DATA OUTPUT                                     #
##############################################################################
[[outputs.file]]
  files = ["stdout"]


[[outputs.prometheus_client]]
  # HTTP port to listen on
  listen = ":9004"